Add retries to pack installation
On first boot, st2 takes a moment to initialize, and if you hit
a pack installation command at the wrong time, you are liable
to run into something like this:

```
/Stage[main]/St2::Packs/St2::Pack[hubot]/Exec[install-st2-pack-hubot]/returns:
  ERROR: HTTPConnectionPool(host='localhost', port=9101): Max retries exceeded
  with url: /v1/actions/packs.install (Caused by <class 'socket.error'>:
  [Errno 111] Connection refused)
```

This commit purposely introduces retries into pack installation with
a 10 second back-off time period in order to allow successful convergence
on the first pass.